import type { RouteContext } from "@emulators/core";
import { apsAuth } from "../auth.js";
import { getApsStore } from "../store.js";

const VIEWABLE_INPUT_FORMATS = [
  "3dm",
  "3ds",
  "3dxml",
  "a",
  "asm",
  "axm",
  "brd",
  "catpart",
  "catproduct",
  "cgr",
  "collaboration",
  "dae",
  "ddx",
  "ddz",
  "dgk",
  "dgn",
  "dlv3",
  "dmt",
  "dwf",
  "dwfx",
  "dwg",
  "dwt",
  "dxf",
  "emodel",
  "exp",
  "f3d",
  "fbrd",
  "fbx",
  "fsch",
  "g",
  "gbxml",
  "glb",
  "gltf",
  "iam",
  "idw",
  "ifc",
  "ige",
  "iges",
  "igs",
  "ipt",
  "iwm",
  "jt",
  "max",
  "model",
  "mpf",
  "msr",
  "neu",
  "nwc",
  "nwd",
  "obj",
  "osb",
  "par",
  "pdf",
  "pmlprj",
  "pmlprjz",
  "prt",
  "psm",
  "psmodel",
  "rvm",
  "rvt",
  "sab",
  "sat",
  "sch",
  "session",
  "skp",
  "sldasm",
  "sldprt",
  "smb",
  "smt",
  "ste",
  "step",
  "stl",
  "stla",
  "stlb",
  "stp",
  "stpz",
  "usd",
  "usda",
  "usdc",
  "usdz",
  "vpb",
  "vue",
  "wire",
  "x_b",
  "x_t",
  "xas",
  "xpr",
  "zip",
  "asm\\.\\d+$",
  "neu\\.\\d+$",
  "prt\\.\\d+$",
];

const SUPPORTED_FORMATS = {
  formats: {
    annotations: ["rvt"],
    dwg: ["f2d", "f3d", "rvt", "slddrw"],
    f3d: [
      "123dx",
      "3dm",
      "3mf",
      "asm",
      "atfx",
      "bdf",
      "catpart",
      "catproduct",
      "cgr",
      "dwg",
      "dxf",
      "emn",
      "fbx",
      "g",
      "iam",
      "ige",
      "iges",
      "igs",
      "ipt",
      "jt",
      "neu",
      "obj",
      "par",
      "pcbdata",
      "pcbxml",
      "prt",
      "sab",
      "sat",
      "skp",
      "sldasm",
      "sldprt",
      "smb",
      "smt",
      "sta",
      "ste",
      "step",
      "stl",
      "stp",
      "wire",
      "x_b",
      "x_t",
      "xml",
      "asm\\.\\d+$",
      "neu\\.\\d+$",
      "prt\\.\\d+$",
    ],
    fbx: ["f3d"],
    ifc: ["rvt"],
    iges: ["f3d", "fbx", "iam", "ipt", "wire"],
    obj: [
      "asm",
      "f3d",
      "fbx",
      "iam",
      "ipt",
      "neu",
      "prt",
      "sldasm",
      "sldprt",
      "smb",
      "smt",
      "step",
      "stp",
      "stpz",
      "wire",
      "x_b",
      "x_t",
      "asm\\.\\d+$",
      "neu\\.\\d+$",
      "prt\\.\\d+$",
    ],
    step: ["f3d", "fbx", "iam", "ipt", "smb", "smt", "wire"],
    stl: ["f3d", "fbx", "iam", "ipt", "wire"],
    svf: VIEWABLE_INPUT_FORMATS,
    svf2: VIEWABLE_INPUT_FORMATS,
    thumbnail: [...VIEWABLE_INPUT_FORMATS, "axmf", "dwgx", "f2d", "flbr", "fprj", "rva"],
  },
};

export function modelDerivativeRoutes({ app, store }: RouteContext): void {
  const aps = getApsStore(store);
  app.use("/modelderivative/v2/*", apsAuth(store, { scopes: ["data:read"] }));

  app.get("/modelderivative/v2/designdata/formats", (c) => c.json(SUPPORTED_FORMATS));

  app.get("/modelderivative/v2/designdata/:urn/manifest", (c) => {
    const manifest = aps.manifests.findOneBy("urn", c.req.param("urn"));
    if (!manifest) return c.body(null, 404);
    return c.json({
      type: manifest.type,
      hasThumbnail: manifest.hasThumbnail,
      status: manifest.status,
      progress: manifest.progress,
      region: manifest.region,
      urn: manifest.urn,
      version: manifest.version,
      derivatives: manifest.derivatives,
    });
  });
}
