export const APS_WEBHOOK_REGIONS = ["US", "EMEA", "AUS", "CAN", "DEU", "IND", "JPN", "GBR"] as const;

const REGION_SET: ReadonlySet<string> = new Set(APS_WEBHOOK_REGIONS);

export function parseWebhookRegion(value: string): string | null {
  const normalized = value.toUpperCase();
  return REGION_SET.has(normalized) ? normalized : null;
}

export const APS_WEBHOOK_EVENTS: Record<string, string[]> = {
  data: [
    "dm.version.added",
    "dm.version.modified",
    "dm.version.deleted",
    "dm.version.moved",
    "dm.version.moved.out",
    "dm.version.copied",
    "dm.version.copied.out",
    "dm.lineage.reserved",
    "dm.lineage.unreserved",
    "dm.lineage.updated",
    "dm.folder.added",
    "dm.folder.modified",
    "dm.folder.deleted",
    "dm.folder.purged",
    "dm.folder.moved",
    "dm.folder.moved.out",
    "dm.folder.copied",
    "dm.folder.copied.out",
    "dm.operation.started",
    "dm.operation.completed",
  ],
  derivative: ["extraction.finished", "extraction.updated"],
  "adsk.c4r": ["model.sync", "model.publish"],
  "adsk.flc.production": [
    "item.clone",
    "item.create",
    "item.lock",
    "item.release",
    "item.unlock",
    "item.update",
    "workflow.transition",
  ],
  "autodesk.construction.cost": [
    "budget.created-1.0",
    "budget.updated-1.0",
    "budget.deleted-1.0",
    "budgetPayment.created-1.0",
    "budgetPayment.updated-1.0",
    "budgetPayment.deleted-1.0",
    "contract.created-1.0",
    "contract.updated-1.0",
    "contract.deleted-1.0",
    "cor.created-1.0",
    "cor.updated-1.0",
    "cor.deleted-1.0",
    "costPayment.created-1.0",
    "costPayment.updated-1.0",
    "costPayment.deleted-1.0",
    "expense.created-1.0",
    "expense.updated-1.0",
    "expense.deleted-1.0",
    "expenseItem.created-1.0",
    "expenseItem.updated-1.0",
    "expenseItem.deleted-1.0",
    "mainContract.created-1.0",
    "mainContract.updated-1.0",
    "mainContract.deleted-1.0",
    "mainContractItem.created-1.0",
    "mainContractItem.updated-1.0",
    "mainContractItem.deleted-1.0",
    "oco.created-1.0",
    "oco.updated-1.0",
    "oco.deleted-1.0",
    "pco.created-1.0",
    "pco.updated-1.0",
    "pco.deleted-1.0",
    "project.initialized-1.0",
    "rfq.created-1.0",
    "rfq.updated-1.0",
    "rfq.deleted-1.0",
    "scheduleOfValue.created-1.0",
    "scheduleOfValue.updated-1.0",
    "scheduleOfValue.deleted-1.0",
    "sco.created-1.0",
    "sco.updated-1.0",
    "sco.deleted-1.0",
    "segmentValue.created-1.0",
    "segmentValue.updated-1.0",
    "segmentValue.deleted-1.0",
  ],
  "autodesk.construction.bc": [
    "bid.created",
    "opportunity.comment.created",
    "opportunity.comment.deleted",
    "opportunity.comment.updated",
    "opportunity.created",
    "opportunity.status.updated",
  ],
  "autodesk.construction.issues": [
    "issue.created-1.0",
    "issue.updated-1.0",
    "issue.deleted-1.0",
    "issue.restored-1.0",
    "issue.unlinked-1.0",
  ],
  "autodesk.construction.reviews": ["review.created-1.0", "review.closed-1.0"],
  "adsk.tandem": ["dt.alert", "dt.mutation", "dt.applyTemplate", "dt.removeTemplate"],
};
